import type { EntityId, RequestContext } from "@qooqnos/core";
import { DatabaseError, D1Database, Repository } from "@qooqnos/database";
import type { SocialCommentRecord, SocialEngagementRecord, SocialEngagementType, SocialFollowRecord, SocialFollowTargetType, SocialTargetType } from "./types";

export class SocialEngagementRepository extends Repository {
  constructor(database: D1Database) { super(database); }
  async follow(context: RequestContext, input: { id: EntityId; targetType: SocialFollowTargetType; targetId: EntityId; now: string }): Promise<SocialFollowRecord> {
    const actor=this.requireActor(context); if(input.targetType==="user"&&input.targetId===actor) throw new DatabaseError("Users cannot follow themselves");
    const scope=await this.resolveScope(context,input.targetType,input.targetId);
    const existing=await this.database.first<SocialFollowRecord>("SELECT id,actor_user_id AS actorUserId,target_type AS targetType,target_id AS targetId,organization_id AS organizationId,workspace_id AS workspaceId,status,created_at AS createdAt,updated_at AS updatedAt FROM social_follows WHERE actor_user_id=? AND target_type=? AND target_id=? AND status='active' LIMIT 1",actor,input.targetType,input.targetId);
    if(existing)return existing;
    const id=input.id;
    await this.database.transaction([
      {sql:"INSERT INTO social_follows (id,actor_user_id,target_type,target_id,organization_id,workspace_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?, 'active',?,?)",params:[id,actor,input.targetType,input.targetId,scope.organizationId,scope.workspaceId,input.now,input.now]},
      {sql:"INSERT INTO outbox_events (id,event_type,event_version,aggregate_type,aggregate_id,organization_id,workspace_id,payload_json,status,attempts,available_at,occurred_at,published_at) VALUES (?,?,?,?,?,?,?,?,'pending',0,?,?,NULL)",params:[id+":created","social.follow.created",1,"SocialFollow",id,scope.organizationId,scope.workspaceId,JSON.stringify({actorUserId:actor,targetType:input.targetType,targetId:input.targetId}),input.now,input.now]}
    ]);
    return this.getFollow(context,id);
  }
  async removeFollow(context:RequestContext,id:EntityId,now:string):Promise<SocialFollowRecord>{const actor=this.requireActor(context);const c=await this.getFollow(context,id);if(c.actorUserId!==actor)throw new DatabaseError("Only the follow owner can remove the follow");if(c.status==="removed")return c;await this.database.transaction([{sql:"UPDATE social_follows SET status='removed',updated_at=? WHERE id=? AND status='active'",params:[now,id]},{sql:"INSERT INTO outbox_events (id,event_type,event_version,aggregate_type,aggregate_id,organization_id,workspace_id,payload_json,status,attempts,available_at,occurred_at,published_at) VALUES (?,?,?,?,?,?,?,?,'pending',0,?,?,NULL)",params:[id+":removed","social.follow.removed",1,"SocialFollow",id,c.organizationId,c.workspaceId,JSON.stringify({actorUserId:actor,targetType:c.targetType,targetId:c.targetId}),now,now]}]);return this.getFollow(context,id);}
  async engage(context:RequestContext,input:{id:EntityId;targetType:Exclude<SocialTargetType,"user">;targetId:EntityId;engagementType:SocialEngagementType;now:string}):Promise<SocialEngagementRecord>{const actor=this.requireActor(context);const scope=await this.resolveScope(context,input.targetType,input.targetId);const c=await this.database.first<SocialEngagementRecord>("SELECT id,actor_user_id AS actorUserId,target_type AS targetType,target_id AS targetId,engagement_type AS engagementType,organization_id AS organizationId,workspace_id AS workspaceId,status,created_at AS createdAt,updated_at AS updatedAt FROM social_engagements WHERE actor_user_id=? AND target_type=? AND target_id=? AND engagement_type=? AND status='active' LIMIT 1",actor,input.targetType,input.targetId,input.engagementType);if(c)return c;const id=input.id;await this.database.transaction([{sql:"INSERT INTO social_engagements (id,actor_user_id,target_type,target_id,engagement_type,organization_id,workspace_id,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'active',?,?)",params:[id,actor,input.targetType,input.targetId,input.engagementType,scope.organizationId,scope.workspaceId,input.now,input.now]},{sql:"INSERT INTO outbox_events (id,event_type,event_version,aggregate_type,aggregate_id,organization_id,workspace_id,payload_json,status,attempts,available_at,occurred_at,published_at) VALUES (?,?,?,?,?,?,?,?,'pending',0,?,?,NULL)",params:[id+":created","social."+input.engagementType+".created",1,"SocialEngagement",id,scope.organizationId,scope.workspaceId,JSON.stringify({actorUserId:actor,targetType:input.targetType,targetId:input.targetId,engagementType:input.engagementType}),input.now,input.now]}]);return this.getEngagement(context,id);}
  async removeEngagement(context:RequestContext,id:EntityId,now:string):Promise<SocialEngagementRecord>{const actor=this.requireActor(context);const c=await this.getEngagement(context,id);if(c.actorUserId!==actor)throw new DatabaseError("Only the engagement owner can remove the engagement");if(c.status==="removed")return c;await this.database.transaction([{sql:"UPDATE social_engagements SET status='removed',updated_at=? WHERE id=? AND status='active'",params:[now,id]},{sql:"INSERT INTO outbox_events (id,event_type,event_version,aggregate_type,aggregate_id,organization_id,workspace_id,payload_json,status,attempts,available_at,occurred_at,published_at) VALUES (?,?,?,?,?,?,?,?,'pending',0,?,?,NULL)",params:[id+":removed","social."+c.engagementType+".removed",1,"SocialEngagement",id,c.organizationId,c.workspaceId,JSON.stringify({actorUserId:actor,targetType:c.targetType,targetId:c.targetId,engagementType:c.engagementType}),now,now]}]);return this.getEngagement(context,id);}
  async comment(context:RequestContext,input:{id:EntityId;targetType:Exclude<SocialTargetType,"user">;targetId:EntityId;body:string;idempotencyKey:string;now:string}):Promise<SocialCommentRecord>{const actor=this.requireActor(context);const body=input.body.trim();const key=input.idempotencyKey.trim();if(!body)throw new DatabaseError("Comment body is required");if(body.length>4000)throw new DatabaseError("Comment body is too long");if(!key)throw new DatabaseError("Comment idempotency key is required");const scope=await this.resolveScope(context,input.targetType,input.targetId);const prior=await this.database.first<SocialCommentRecord>("SELECT id,actor_user_id AS actorUserId,target_type AS targetType,target_id AS targetId,organization_id AS organizationId,workspace_id AS workspaceId,body,moderation_status AS moderationStatus,idempotency_key AS idempotencyKey,created_at AS createdAt,updated_at AS updatedAt FROM social_comments WHERE actor_user_id=? AND idempotency_key=? LIMIT 1",actor,key);if(prior)return prior;const id=input.id;await this.database.transaction([{sql:"INSERT INTO social_comments (id,actor_user_id,target_type,target_id,organization_id,workspace_id,body,moderation_status,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'pending',?,?,?)",params:[id,actor,input.targetType,input.targetId,scope.organizationId,scope.workspaceId,body,key,input.now,input.now]},{sql:"INSERT INTO outbox_events (id,event_type,event_version,aggregate_type,aggregate_id,organization_id,workspace_id,payload_json,status,attempts,available_at,occurred_at,published_at) VALUES (?,?,?,?,?,?,?,?,'pending',0,?,?,NULL)",params:[id+":created","social.comment.created",1,"SocialComment",id,scope.organizationId,scope.workspaceId,JSON.stringify({actorUserId:actor,targetType:input.targetType,targetId:input.targetId}),input.now,input.now]}]);return this.getComment(context,id);}
  async removeComment(context:RequestContext,id:EntityId,now:string):Promise<SocialCommentRecord>{const actor=this.requireActor(context);const c=await this.getComment(context,id);if(c.actorUserId!==actor)throw new DatabaseError("Only the comment owner can remove the comment");if(c.moderationStatus==="removed")return c;await this.database.transaction([{sql:"UPDATE social_comments SET moderation_status='removed',updated_at=? WHERE id=? AND moderation_status!='removed'",params:[now,id]},{sql:"INSERT INTO outbox_events (id,event_type,event_version,aggregate_type,aggregate_id,organization_id,workspace_id,payload_json,status,attempts,available_at,occurred_at,published_at) VALUES (?,?,?,?,?,?,?,?,'pending',0,?,?,NULL)",params:[id+":removed","social.comment.removed",1,"SocialComment",id,c.organizationId,c.workspaceId,JSON.stringify({actorUserId:actor,targetType:c.targetType,targetId:c.targetId}),now,now]}]);return this.getComment(context,id);}
  async activity(context: RequestContext, limit = 20): Promise<unknown[]> {
    const actor = this.requireActor(context);
    const safeLimit = Math.min(Math.max(limit, 1), 50);
    return this.database.all<unknown>(
      "SELECT id,event_type AS eventType,event_version AS eventVersion,aggregate_type AS aggregateType,aggregate_id AS aggregateId,payload_json AS payloadJson,occurred_at AS occurredAt FROM outbox_events WHERE event_type LIKE 'social.%' AND json_extract(payload_json,'$.actorUserId')=? ORDER BY occurred_at DESC LIMIT " + safeLimit,
      actor,
    );
  }

  async getFollow(context:RequestContext,id:EntityId):Promise<SocialFollowRecord>{const actor=this.requireActor(context);const r=await this.database.first<SocialFollowRecord>("SELECT id,actor_user_id AS actorUserId,target_type AS targetType,target_id AS targetId,organization_id AS organizationId,workspace_id AS workspaceId,status,created_at AS createdAt,updated_at AS updatedAt FROM social_follows WHERE id=? LIMIT 1",id);if(!r)throw new DatabaseError("Social follow not found");if(r.actorUserId!==actor)throw new DatabaseError("Social follow is not owned by the authenticated actor");return r;}
  async getEngagement(context:RequestContext,id:EntityId):Promise<SocialEngagementRecord>{const actor=this.requireActor(context);const r=await this.database.first<SocialEngagementRecord>("SELECT id,actor_user_id AS actorUserId,target_type AS targetType,target_id AS targetId,engagement_type AS engagementType,organization_id AS organizationId,workspace_id AS workspaceId,status,created_at AS createdAt,updated_at AS updatedAt FROM social_engagements WHERE id=? LIMIT 1",id);if(!r)throw new DatabaseError("Social engagement not found");if(r.actorUserId!==actor)throw new DatabaseError("Social engagement is not owned by the authenticated actor");return r;}
  async getComment(context:RequestContext,id:EntityId):Promise<SocialCommentRecord>{const actor=this.requireActor(context);const r=await this.database.first<SocialCommentRecord>("SELECT id,actor_user_id AS actorUserId,target_type AS targetType,target_id AS targetId,organization_id AS organizationId,workspace_id AS workspaceId,body,moderation_status AS moderationStatus,idempotency_key AS idempotencyKey,created_at AS createdAt,updated_at AS updatedAt FROM social_comments WHERE id=? LIMIT 1",id);if(!r)throw new DatabaseError("Social comment not found");if(r.actorUserId!==actor)throw new DatabaseError("Social comment is not owned by the authenticated actor");return r;}
  private requireActor(context:RequestContext):EntityId{if(!context.actorId)throw new DatabaseError("Authenticated actor is required");return context.actorId;}
  private async resolveScope(context:RequestContext,targetType:SocialTargetType,targetId:EntityId):Promise<{organizationId:EntityId|null;workspaceId:EntityId|null}>{if(targetType==="user"){const u=await this.database.first<{id:EntityId}>("SELECT id FROM users WHERE id=? AND status='active' LIMIT 1",targetId);if(!u)throw new DatabaseError("Social target user not found");return {organizationId:null,workspaceId:null};}if(targetType==="business"){const b=await this.database.first<{id:EntityId;organizationId:EntityId;workspaceId:EntityId}>("SELECT id,organization_id AS organizationId,workspace_id AS workspaceId FROM businesses WHERE id=? AND status='active' AND publication_status='published' LIMIT 1",targetId);if(!b)throw new DatabaseError("Social target business not found or not public");this.assertWorkspace(context,b.organizationId,b.workspaceId);return b;}const table=targetType==="product"?"products":targetType==="service"?"services":null;if(!table)throw new DatabaseError("Social post targets are not yet backed by a canonical supply/content entity");const sql="SELECT b.organization_id AS organizationId,b.workspace_id AS workspaceId FROM "+table+" s INNER JOIN businesses b ON b.id=s.business_id WHERE s.id=? AND s.status='active' AND b.status='active' AND b.publication_status='published' LIMIT 1";const row=await this.database.first<{organizationId:EntityId;workspaceId:EntityId}>(sql,targetId);if(!row)throw new DatabaseError("Social target is not public");this.assertWorkspace(context,row.organizationId,row.workspaceId);return row;}
  private assertWorkspace(context:RequestContext,organizationId:EntityId,workspaceId:EntityId):void{if(context.tenantId&&context.tenantId!==organizationId)throw new DatabaseError("Social target crosses organization boundary");if(context.workspaceId&&context.workspaceId!==workspaceId)throw new DatabaseError("Social target crosses workspace boundary");}
}