-- Canonical Social Engagement / Graph boundary.
CREATE TABLE social_follows (id TEXT PRIMARY KEY, actor_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, target_type TEXT NOT NULL CHECK (target_type IN ('user','business')), target_id TEXT NOT NULL, organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE, workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE, status TEXT NOT NULL CHECK (status IN ('active','removed')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX uq_social_follows_active ON social_follows(actor_user_id, target_type, target_id) WHERE status = 'active';
CREATE INDEX idx_social_follows_target ON social_follows(target_type, target_id, status);
CREATE TABLE social_engagements (id TEXT PRIMARY KEY, actor_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, target_type TEXT NOT NULL CHECK (target_type IN ('product','service','post','business')), target_id TEXT NOT NULL, engagement_type TEXT NOT NULL CHECK (engagement_type IN ('like','save')), organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE, workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE, status TEXT NOT NULL CHECK (status IN ('active','removed')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX uq_social_engagement_active ON social_engagements(actor_user_id, target_type, target_id, engagement_type) WHERE status = 'active';
CREATE INDEX idx_social_engagement_target ON social_engagements(target_type, target_id, engagement_type, status);
CREATE TABLE social_comments (id TEXT PRIMARY KEY, actor_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, target_type TEXT NOT NULL CHECK (target_type IN ('product','service','post','business')), target_id TEXT NOT NULL, organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE, workspace_id TEXT REFERENCES workspaces(id) ON DELETE CASCADE, body TEXT NOT NULL, moderation_status TEXT NOT NULL CHECK (moderation_status IN ('pending','visible','hidden','removed')), idempotency_key TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(actor_user_id, idempotency_key));
CREATE INDEX idx_social_comments_target ON social_comments(target_type, target_id, moderation_status, created_at);
CREATE TRIGGER trg_social_follow_workspace_scope BEFORE INSERT ON social_follows FOR EACH ROW WHEN NEW.target_type = 'business' AND (NEW.organization_id IS NULL OR NEW.workspace_id IS NULL OR NOT EXISTS (SELECT 1 FROM businesses b WHERE b.id = NEW.target_id AND b.organization_id = NEW.organization_id AND b.workspace_id = NEW.workspace_id)) BEGIN SELECT RAISE(ABORT, 'Social business follow crosses organization/workspace boundary'); END;
CREATE TRIGGER trg_social_engagement_workspace_scope BEFORE INSERT ON social_engagements FOR EACH ROW WHEN NEW.target_type = 'business' AND (NEW.organization_id IS NULL OR NEW.workspace_id IS NULL OR NOT EXISTS (SELECT 1 FROM businesses b WHERE b.id = NEW.target_id AND b.organization_id = NEW.organization_id AND b.workspace_id = NEW.workspace_id)) BEGIN SELECT RAISE(ABORT, 'Social business engagement crosses organization/workspace boundary'); END;
CREATE TRIGGER trg_social_comment_workspace_scope BEFORE INSERT ON social_comments FOR EACH ROW WHEN NEW.target_type = 'business' AND (NEW.organization_id IS NULL OR NEW.workspace_id IS NULL OR NOT EXISTS (SELECT 1 FROM businesses b WHERE b.id = NEW.target_id AND b.organization_id = NEW.organization_id AND b.workspace_id = NEW.workspace_id)) BEGIN SELECT RAISE(ABORT, 'Social business comment crosses organization/workspace boundary'); END;