export type ExportCalendar = "gregorian" | "persian" | "islamic";
export interface ExportDocumentMetadata { readonly documentType:string; readonly title:string; readonly generatedAt:string; readonly sourceCapability:string; readonly resourceScope:string; readonly organizationId:string; readonly workspaceId:string; readonly actorId:string; }
export interface ExportDocumentTable { readonly columns:readonly string[]; readonly rows:readonly (readonly string[])[]; }
export interface ExportDocumentSection { readonly title:string; readonly blocks:readonly string[]; readonly tables:readonly ExportDocumentTable[]; }
export interface ExportDocumentAttachment { readonly artifactReference:string; readonly filename:string; readonly mediaType:string; }
export interface ExportDocument { readonly metadata:ExportDocumentMetadata; readonly locale:string; readonly timezone:string; readonly calendar:ExportCalendar; readonly template:{readonly id:string;readonly version:number}; readonly branding?:Readonly<Record<string,string>>; readonly header:readonly string[]; readonly sections:readonly ExportDocumentSection[]; readonly footer:readonly string[]; readonly attachments:readonly ExportDocumentAttachment[]; readonly provenance:Readonly<Record<string,string>>; readonly integrity:{readonly snapshotHash:string}; }
export interface ExportDocumentQuery { readonly query:(request:{readonly capability:string;readonly resourceScope:string})=>Promise<readonly ExportDocumentSection[]>; }
export interface ExportDocumentRequest { readonly metadata:ExportDocumentMetadata; readonly locale:string; readonly timezone:string; readonly calendar:ExportCalendar; readonly template:{readonly id:string;readonly version:number}; readonly branding?:Readonly<Record<string,string>>; readonly header?:readonly string[]; readonly footer?:readonly string[]; readonly attachments?:readonly ExportDocumentAttachment[]; readonly provenance?:Readonly<Record<string,string>>; }
export async function composeExportDocument(request:ExportDocumentRequest,query:ExportDocumentQuery):Promise<ExportDocument>{
 validateExportRequest(request); const sections=(await query.query({capability:request.metadata.sourceCapability,resourceScope:request.metadata.resourceScope})).map(s=>({title:s.title,blocks:[...s.blocks],tables:s.tables.map(t=>({columns:[...t.columns],rows:t.rows.map(r=>[...r])}))}));
 const provenance={...(request.provenance??{}),sourceCapability:request.metadata.sourceCapability,resourceScope:request.metadata.resourceScope,templateId:request.template.id,templateVersion:String(request.template.version)};
 const snapshotHash=await sha256(JSON.stringify({metadata:request.metadata,locale:request.locale,timezone:request.timezone,calendar:request.calendar,template:request.template,sections,attachments:request.attachments??[],provenance}));
 const document:ExportDocument={metadata:request.metadata,locale:request.locale,timezone:request.timezone,calendar:request.calendar,template:request.template,...(request.branding?{branding:request.branding}:{}),header:request.header??[],sections,footer:request.footer??[],attachments:request.attachments??[],provenance,integrity:{snapshotHash}}; validateExportDocument(document); return document;
}
export function validateExportDocument(d:ExportDocument):void{if(!d.metadata.organizationId||!d.metadata.workspaceId)throw new Error("ExportDocument tenant scope is required");if(!d.metadata.actorId)throw new Error("ExportDocument actor is required");if(!d.metadata.sourceCapability||!d.metadata.resourceScope)throw new Error("ExportDocument source scope is required");if(!d.template.id||d.template.version<1)throw new Error("ExportDocument template/version is invalid");if(!/^[a-f0-9]{64}$/.test(d.integrity.snapshotHash))throw new Error("ExportDocument snapshot hash is invalid");}
function validateExportRequest(r:ExportDocumentRequest):void{if(!r.locale.trim()||!r.timezone.trim())throw new Error("ExportDocument locale/timezone is required");if(!r.metadata.documentType.trim()||!r.metadata.title.trim()||!r.metadata.generatedAt.trim())throw new Error("ExportDocument metadata is required");if(!r.metadata.organizationId.trim()||!r.metadata.workspaceId.trim())throw new Error("ExportDocument tenant scope is required");}
async function sha256(v:string):Promise<string>{const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d),b=>b.toString(16).padStart(2,"0")).join("");}